# The 'core' library is distrbuted with the Rust compiler and is only vaid for
# the default supported host triples. In order to support our custom
# x86_64-rustos host we need to recompile the core library first.
[unstable]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-rustos.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
